### ISSUE TITLE
Consider removing ext dependencies

### ISSUE THREAD

**Issue by rnag** [bitranox/pprint3x#1]
* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
request feature or suggest a design change

* **What is the current behavior?**
installing this backport supposedly installs all kinds of unnecessary 3rd party libraries

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
n/a

* **What is the expected behavior?**
no dependencies outside of stdlib are included - including perhaps `dataclasses` backport for python 3.6

* **What is the motivation / use case for changing the behavior?**
so more people in community hopefully can use this backport. also better maintainability i suppose, since less dependencies.

Take a look here:
https://github.com/bitranox/pprint3x/blob/master/requirements.txt#L2-L5

Ideally there'd be only that one line, for the dataclasses backport on 3.6. Right now there's a few additional dependencies not needed for someone to import `ppprint` in Python code - for example, the `click` external dependency which ostensibly is for a CLI parser. This is nice for command-line support, but in general use case, especially as it's designed for a backport, I'm not sure all these external depedencies are necessary.

If still want to keep the external dependencies, I'd suggest adding an `extra` keyword in setup.py, and adding those dependencies there. This extra can be named as "cli", so for example installing `pprint3[cli]` would install all the dependencies needed for the CLI tool. Again, just a thought.

* **Please tell us about your environment:**

- Release Number of the Repository used : 
- Python Version : 3.7
- OS, OS Version : Mac OS X

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)
n/a

**Comment by bitranox** [comment]
thanks for the suggestion - It came from my default "PizzaCutter" Python Project Template.

So I adopted the PizzaCutter Template and got rid of the CLI and unnecessary imports.
Good suggestion, thanks.

I saw You forged cookiecutter, so You might look into PizzaCutter ...

I mentioned Your name as credits in the version history, I hope You dont mind.

**Comment by rnag** [comment]
> I mentioned Your name as credits in the version history, I hope You dont mind.

Sure, no problem at all! I also certainly appreciate being mentioned in the change log, even though I feel like majority of the credit for the refactor/cleanup goes to you 👍 

I've also just tested using the backported `pprint` function in a Python 3.7 environment, and confirmed all looks good. I get the same output as in my 3.10 environment, which is great.

One small change I would also suggest, would be to update documentation on PyPI to include a brief example of the Usage. 

For example, I suppose this might be the intended usage:

    from pprint3x import pprint

Also the default `pprint` import in Python 3.7 (which is mentioned in the linked docs on `pprint`) would here import the builtin module, which of course does not have the improvements from `pprint` in 3.10:

    from pprint import pprint

**Comment by bitranox** [comment]
> One small change I would also suggest, would be to update documentation on PyPI to include a brief example of the Usage.

ok, done.

>   Sure, no problem at all! I also certainly appreciate being mentioned in the change log, even though I feel like majority of the 
  credit for the refactor/cleanup goes to you 👍

to give it a thought and to test deserves appreciation. the changes themselves where trivial ... 

BTW, I did the same for pathlib ... - check it out : 

https://github.com/bitranox/pathlib3x
